// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Softjourn.SJCoins.iOS
{
	public partial class FavoritesTableViewCell : UITableViewCell
	{
		public FavoritesTableViewCell (IntPtr handle) : base (handle)
		{
		}
	}
}
