// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Softjourn.SJCoins.iOS
{
	public partial class HomeCollectionViewCell : UICollectionViewCell
	{
		public HomeCollectionViewCell (IntPtr handle) : base (handle)
		{
		}
	}
}
