//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softjourn.SJCoins.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ServerErrorResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServerErrorResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Softjourn.SJCoins.Core.Resources.ServerErrorResources", typeof(ServerErrorResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not clear request to server.
        /// </summary>
        public static string server_error_400 {
            get {
                return ResourceManager.GetString("server_error_400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your session has expired. Please log in again..
        /// </summary>
        public static string server_error_401 {
            get {
                return ResourceManager.GetString("server_error_401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource is not found.
        /// </summary>
        public static string server_error_404 {
            get {
                return ResourceManager.GetString("server_error_404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no machines.
        /// </summary>
        public static string server_error_40401 {
            get {
                return ResourceManager.GetString("server_error_40401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not such machine.
        /// </summary>
        public static string server_error_40402 {
            get {
                return ResourceManager.GetString("server_error_40402", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data could not be downloaded. Please try again later.
        /// </summary>
        public static string server_error_40403 {
            get {
                return ResourceManager.GetString("server_error_40403", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep Calm! Chosen product is not available now. Please try to refresh products list.
        /// </summary>
        public static string server_error_40404 {
            get {
                return ResourceManager.GetString("server_error_40404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data could not be downloaded. Please try again later.
        /// </summary>
        public static string server_error_40405 {
            get {
                return ResourceManager.GetString("server_error_40405", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no such product. Please try to refresh products list.
        /// </summary>
        public static string server_error_40406 {
            get {
                return ResourceManager.GetString("server_error_40406", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no such product. Please try to refresh products list.
        /// </summary>
        public static string server_error_40407 {
            get {
                return ResourceManager.GetString("server_error_40407", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately your History could not be downloaded.
        /// </summary>
        public static string server_error_40408 {
            get {
                return ResourceManager.GetString("server_error_40408", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account is not correct and could not be found.
        /// </summary>
        public static string server_error_40409 {
            get {
                return ResourceManager.GetString("server_error_40409", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find your amount. Please contact administrator.
        /// </summary>
        public static string server_error_40410 {
            get {
                return ResourceManager.GetString("server_error_40410", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is some conflict with data on the server.
        /// </summary>
        public static string server_error_409 {
            get {
                return ResourceManager.GetString("server_error_409", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ooops… You have not enough money to buy product.
        /// </summary>
        public static string server_error_40901 {
            get {
                return ResourceManager.GetString("server_error_40901", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product is already in favorites.
        /// </summary>
        public static string server_error_40902 {
            get {
                return ResourceManager.GetString("server_error_40902", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product is not in favorites.
        /// </summary>
        public static string server_error_40903 {
            get {
                return ResourceManager.GetString("server_error_40903", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Such cheque was not issued or already cashed out..
        /// </summary>
        public static string server_error_40906 {
            get {
                return ResourceManager.GetString("server_error_40906", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine is locked by queue. Try again later.
        /// </summary>
        public static string server_error_509 {
            get {
                return ResourceManager.GetString("server_error_509", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right now machine is locked by queue. We know it&apos;s annoying. But please try again later.
        /// </summary>
        public static string server_error_50901 {
            get {
                return ResourceManager.GetString("server_error_50901", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately service is not available right now. Just try again later.
        /// </summary>
        public static string server_error_other {
            get {
                return ResourceManager.GetString("server_error_other", resourceCulture);
            }
        }
    }
}
