// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Softjourn.SJCoins.iOS
{
	public partial class CustomLoginUIButton : UIButton
	{
		public CustomLoginUIButton (IntPtr handle) : base (handle)
		{
		}
	}
}
