//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softjourn.SJCoins.Core.UI.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Softjourn.SJCoins.Core.UI.Resources.StringResources", typeof(StringResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string activity_login_empty_username {
            get {
                return ResourceManager.GetString("activity_login_empty_username", resourceCulture);
            }
        }
        
        internal static string activity_login_invalid_password {
            get {
                return ResourceManager.GetString("activity_login_invalid_password", resourceCulture);
            }
        }
        
        internal static string activity_login_login_failed {
            get {
                return ResourceManager.GetString("activity_login_login_failed", resourceCulture);
            }
        }
        
        internal static string activity_product_take_your_order_message {
            get {
                return ResourceManager.GetString("activity_product_take_your_order_message", resourceCulture);
            }
        }
        
        internal static string app_name {
            get {
                return ResourceManager.GetString("app_name", resourceCulture);
            }
        }
        
        internal static string btn_title_cancel {
            get {
                return ResourceManager.GetString("btn_title_cancel", resourceCulture);
            }
        }
        
        internal static string btn_title_ok {
            get {
                return ResourceManager.GetString("btn_title_ok", resourceCulture);
            }
        }
        
        internal static string internet_turned_off {
            get {
                return ResourceManager.GetString("internet_turned_off", resourceCulture);
            }
        }
        
        internal static string machine_not_selected_toast {
            get {
                return ResourceManager.GetString("machine_not_selected_toast", resourceCulture);
            }
        }
        
        internal static string no_purchases_yet {
            get {
                return ResourceManager.GetString("no_purchases_yet", resourceCulture);
            }
        }
        
        internal static string progress_authenticating {
            get {
                return ResourceManager.GetString("progress_authenticating", resourceCulture);
            }
        }
        
        internal static string progress_loading {
            get {
                return ResourceManager.GetString("progress_loading", resourceCulture);
            }
        }
        
        internal static string there_are_no_items {
            get {
                return ResourceManager.GetString("there_are_no_items", resourceCulture);
            }
        }
        
        internal static string your_balance_is {
            get {
                return ResourceManager.GetString("your_balance_is", resourceCulture);
            }
        }
        
        internal static string error_msg_empty_machines_list {
            get {
                return ResourceManager.GetString("error_msg_empty_machines_list", resourceCulture);
            }
        }
        
        internal static string error_msg_invalid_selected_machine {
            get {
                return ResourceManager.GetString("error_msg_invalid_selected_machine", resourceCulture);
            }
        }
        
        internal static string progress_buying {
            get {
                return ResourceManager.GetString("progress_buying", resourceCulture);
            }
        }
        
        internal static string server_error_bad_username_or_password {
            get {
                return ResourceManager.GetString("server_error_bad_username_or_password", resourceCulture);
            }
        }
        
        internal static string error_not_enough_money {
            get {
                return ResourceManager.GetString("error_not_enough_money", resourceCulture);
            }
        }
        
        internal static string select_source_photo_camera {
            get {
                return ResourceManager.GetString("select_source_photo_camera", resourceCulture);
            }
        }
        
        internal static string select_source_photo_gallery {
            get {
                return ResourceManager.GetString("select_source_photo_gallery", resourceCulture);
            }
        }
        
        internal static string select_strategy_scanning_qr {
            get {
                return ResourceManager.GetString("select_strategy_scanning_qr", resourceCulture);
            }
        }
        
        internal static string select_strategy_generating_qr {
            get {
                return ResourceManager.GetString("select_strategy_generating_qr", resourceCulture);
            }
        }
        
        internal static string error_field_contains_not_digits {
            get {
                return ResourceManager.GetString("error_field_contains_not_digits", resourceCulture);
            }
        }
        
        internal static string error_field_is_empty {
            get {
                return ResourceManager.GetString("error_field_is_empty", resourceCulture);
            }
        }
        
        internal static string error_field_not_enough_money {
            get {
                return ResourceManager.GetString("error_field_not_enough_money", resourceCulture);
            }
        }
        
        internal static string error_field_too_many_characters {
            get {
                return ResourceManager.GetString("error_field_too_many_characters", resourceCulture);
            }
        }
        
        internal static string unknown_code {
            get {
                return ResourceManager.GetString("unknown_code", resourceCulture);
            }
        }
        
        internal static string wallet_was_funded {
            get {
                return ResourceManager.GetString("wallet_was_funded", resourceCulture);
            }
        }
        
        internal static string error_field_zero_amount {
            get {
                return ResourceManager.GetString("error_field_zero_amount", resourceCulture);
            }
        }
        
        internal static string error_not_valid_qr_code {
            get {
                return ResourceManager.GetString("error_not_valid_qr_code", resourceCulture);
            }
        }
    }
}
