//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softjourn.SJCoins.Core.UI.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Softjourn.SJCoins.Core.UI.Resources.StringResources", typeof(StringResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login should not be empty.
        /// </summary>
        public static string activity_login_empty_username {
            get {
                return ResourceManager.GetString("activity_login_empty_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password should not be empty.
        /// </summary>
        public static string activity_login_invalid_password {
            get {
                return ResourceManager.GetString("activity_login_invalid_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol is not allowed.
        /// </summary>
        public static string activity_login_invalid_username {
            get {
                return ResourceManager.GetString("activity_login_invalid_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed.
        /// </summary>
        public static string activity_login_login_failed {
            get {
                return ResourceManager.GetString("activity_login_login_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please take your order.
        /// </summary>
        public static string activity_product_take_your_order_message {
            get {
                return ResourceManager.GetString("activity_product_take_your_order_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SJCoins.
        /// </summary>
        public static string app_name {
            get {
                return ResourceManager.GetString("app_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string btn_title_cancel {
            get {
                return ResourceManager.GetString("btn_title_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string btn_title_ok {
            get {
                return ResourceManager.GetString("btn_title_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Numerical characters allowed.
        /// </summary>
        public static string error_field_contains_not_digits {
            get {
                return ResourceManager.GetString("error_field_contains_not_digits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount should not be empty.
        /// </summary>
        public static string error_field_is_empty {
            get {
                return ResourceManager.GetString("error_field_is_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount is bigger than your balance.
        /// </summary>
        public static string error_field_not_enough_money {
            get {
                return ResourceManager.GetString("error_field_not_enough_money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no active machines. Please try to refresh list.
        /// </summary>
        public static string error_msg_empty_machines_list {
            get {
                return ResourceManager.GetString("error_msg_empty_machines_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid selected machine.
        /// </summary>
        public static string error_msg_invalid_selected_machine {
            get {
                return ResourceManager.GetString("error_msg_invalid_selected_machine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough money!.
        /// </summary>
        public static string error_not_enough_money {
            get {
                return ResourceManager.GetString("error_not_enough_money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Internet connection.
        /// </summary>
        public static string internet_turned_off {
            get {
                return ResourceManager.GetString("internet_turned_off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose machine for correct work of application.
        /// </summary>
        public static string machine_not_selected_toast {
            get {
                return ResourceManager.GetString("machine_not_selected_toast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry… There is no purchases yet.
        /// </summary>
        public static string no_purchases_yet {
            get {
                return ResourceManager.GetString("no_purchases_yet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticating….
        /// </summary>
        public static string progress_authenticating {
            get {
                return ResourceManager.GetString("progress_authenticating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buying.
        /// </summary>
        public static string progress_buying {
            get {
                return ResourceManager.GetString("progress_buying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string progress_loading {
            get {
                return ResourceManager.GetString("progress_loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Camera.
        /// </summary>
        public static string select_source_photo_camera {
            get {
                return ResourceManager.GetString("select_source_photo_camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Gallery.
        /// </summary>
        public static string select_source_photo_gallery {
            get {
                return ResourceManager.GetString("select_source_photo_gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Code.
        /// </summary>
        public static string select_strategy_generating_qr {
            get {
                return ResourceManager.GetString("select_strategy_generating_qr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Code.
        /// </summary>
        public static string select_strategy_scanning_qr {
            get {
                return ResourceManager.GetString("select_strategy_scanning_qr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or password is incorrect.
        /// </summary>
        public static string server_error_bad_username_or_password {
            get {
                return ResourceManager.GetString("server_error_bad_username_or_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently there are no products in this category.
        /// </summary>
        public static string there_are_no_items {
            get {
                return ResourceManager.GetString("there_are_no_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, this code is unknown.
        /// </summary>
        public static string unknown_code {
            get {
                return ResourceManager.GetString("unknown_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your balance is %s coins.
        /// </summary>
        public static string your_balance_is {
            get {
                return ResourceManager.GetString("your_balance_is", resourceCulture);
            }
        }
    }
}
