//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softjourn.SJCoins.Core.UI.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Softjourn.SJCoins.Core.UI.Resources.StringResources", typeof(StringResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login should contain only lower case alphabetical characters.
        /// </summary>
        internal static string activity_login_invalid_email {
            get {
                return ResourceManager.GetString("activity_login_invalid_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password should not be empty.
        /// </summary>
        internal static string activity_login_invalid_password {
            get {
                return ResourceManager.GetString("activity_login_invalid_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed.
        /// </summary>
        internal static string activity_login_login_failed {
            get {
                return ResourceManager.GetString("activity_login_login_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please take your order.
        /// </summary>
        internal static string activity_product_take_your_order_message {
            get {
                return ResourceManager.GetString("activity_product_take_your_order_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SJCoins.
        /// </summary>
        internal static string app_name {
            get {
                return ResourceManager.GetString("app_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Internet connection.
        /// </summary>
        internal static string internet_turned_off {
            get {
                return ResourceManager.GetString("internet_turned_off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose machine for correct work of application.
        /// </summary>
        internal static string machine_not_selected_toast {
            get {
                return ResourceManager.GetString("machine_not_selected_toast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry… There is no purchases yet.
        /// </summary>
        internal static string no_purchases_yet {
            get {
                return ResourceManager.GetString("no_purchases_yet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticating….
        /// </summary>
        internal static string progress_authenticating {
            get {
                return ResourceManager.GetString("progress_authenticating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        internal static string progress_loading {
            get {
                return ResourceManager.GetString("progress_loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not clear request to server.
        /// </summary>
        internal static string server_error_400 {
            get {
                return ResourceManager.GetString("server_error_400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something wrong with your authentication. Check your credentials.
        /// </summary>
        internal static string server_error_401 {
            get {
                return ResourceManager.GetString("server_error_401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource is not found.
        /// </summary>
        internal static string server_error_404 {
            get {
                return ResourceManager.GetString("server_error_404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no machines.
        /// </summary>
        internal static string server_error_40401 {
            get {
                return ResourceManager.GetString("server_error_40401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not such machine.
        /// </summary>
        internal static string server_error_40402 {
            get {
                return ResourceManager.GetString("server_error_40402", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data could not be downloaded. Please try again later.
        /// </summary>
        internal static string server_error_40403 {
            get {
                return ResourceManager.GetString("server_error_40403", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep Calm! Chosen product is not available now. Please try to refresh products list.
        /// </summary>
        internal static string server_error_40404 {
            get {
                return ResourceManager.GetString("server_error_40404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data could not be downloaded. Please try again later.
        /// </summary>
        internal static string server_error_40405 {
            get {
                return ResourceManager.GetString("server_error_40405", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no such product. Please try to refresh products list.
        /// </summary>
        internal static string server_error_40406 {
            get {
                return ResourceManager.GetString("server_error_40406", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no such product. Please try to refresh products list.
        /// </summary>
        internal static string server_error_40407 {
            get {
                return ResourceManager.GetString("server_error_40407", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately your History could not be downloaded.
        /// </summary>
        internal static string server_error_40408 {
            get {
                return ResourceManager.GetString("server_error_40408", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account is not correct and could not be found.
        /// </summary>
        internal static string server_error_40409 {
            get {
                return ResourceManager.GetString("server_error_40409", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find your amount. Please contact administrator.
        /// </summary>
        internal static string server_error_40410 {
            get {
                return ResourceManager.GetString("server_error_40410", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is some conflict with data on the server.
        /// </summary>
        internal static string server_error_409 {
            get {
                return ResourceManager.GetString("server_error_409", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ooops… You have not enough money to buy product.
        /// </summary>
        internal static string server_error_40901 {
            get {
                return ResourceManager.GetString("server_error_40901", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product is already in favorites.
        /// </summary>
        internal static string server_error_40902 {
            get {
                return ResourceManager.GetString("server_error_40902", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product is not in favorites.
        /// </summary>
        internal static string server_error_40903 {
            get {
                return ResourceManager.GetString("server_error_40903", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine is locked by queue. Try again later.
        /// </summary>
        internal static string server_error_509 {
            get {
                return ResourceManager.GetString("server_error_509", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right now machine is locked by queue. We know it&apos;s annoying. But please try again later.
        /// </summary>
        internal static string server_error_50901 {
            get {
                return ResourceManager.GetString("server_error_50901", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately service is not available right now. Just try again later.
        /// </summary>
        internal static string server_error_other {
            get {
                return ResourceManager.GetString("server_error_other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently there are no products in this category.
        /// </summary>
        internal static string there_are_no_items {
            get {
                return ResourceManager.GetString("there_are_no_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your balance is %s coins.
        /// </summary>
        internal static string your_balance_is {
            get {
                return ResourceManager.GetString("your_balance_is", resourceCulture);
            }
        }
    }
}
