//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softjourn.SJCoins.Core.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Softjourn.SJCoins.Core.Resources.StringResources", typeof(StringResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string server_error_400 {
            get {
                return ResourceManager.GetString("server_error_400", resourceCulture);
            }
        }
        
        internal static string server_error_401 {
            get {
                return ResourceManager.GetString("server_error_401", resourceCulture);
            }
        }
        
        internal static string server_error_404 {
            get {
                return ResourceManager.GetString("server_error_404", resourceCulture);
            }
        }
        
        internal static string server_error_40401 {
            get {
                return ResourceManager.GetString("server_error_40401", resourceCulture);
            }
        }
        
        internal static string server_error_40402 {
            get {
                return ResourceManager.GetString("server_error_40402", resourceCulture);
            }
        }
        
        internal static string server_error_40403 {
            get {
                return ResourceManager.GetString("server_error_40403", resourceCulture);
            }
        }
        
        internal static string server_error_40404 {
            get {
                return ResourceManager.GetString("server_error_40404", resourceCulture);
            }
        }
        
        internal static string server_error_40405 {
            get {
                return ResourceManager.GetString("server_error_40405", resourceCulture);
            }
        }
        
        internal static string server_error_40406 {
            get {
                return ResourceManager.GetString("server_error_40406", resourceCulture);
            }
        }
        
        internal static string server_error_40407 {
            get {
                return ResourceManager.GetString("server_error_40407", resourceCulture);
            }
        }
        
        internal static string server_error_40408 {
            get {
                return ResourceManager.GetString("server_error_40408", resourceCulture);
            }
        }
        
        internal static string server_error_40409 {
            get {
                return ResourceManager.GetString("server_error_40409", resourceCulture);
            }
        }
        
        internal static string server_error_40410 {
            get {
                return ResourceManager.GetString("server_error_40410", resourceCulture);
            }
        }
        
        internal static string server_error_409 {
            get {
                return ResourceManager.GetString("server_error_409", resourceCulture);
            }
        }
        
        internal static string server_error_40901 {
            get {
                return ResourceManager.GetString("server_error_40901", resourceCulture);
            }
        }
        
        internal static string server_error_40902 {
            get {
                return ResourceManager.GetString("server_error_40902", resourceCulture);
            }
        }
        
        internal static string server_error_40903 {
            get {
                return ResourceManager.GetString("server_error_40903", resourceCulture);
            }
        }
        
        internal static string server_error_40906 {
            get {
                return ResourceManager.GetString("server_error_40906", resourceCulture);
            }
        }
        
        internal static string server_error_509 {
            get {
                return ResourceManager.GetString("server_error_509", resourceCulture);
            }
        }
        
        internal static string server_error_50901 {
            get {
                return ResourceManager.GetString("server_error_50901", resourceCulture);
            }
        }
        
        internal static string server_error_other {
            get {
                return ResourceManager.GetString("server_error_other", resourceCulture);
            }
        }
    }
}
